---
driver:
  # using docker to test
  name: docker
  privileged: true

provisioner:
  # use an ansible playbook to provision our server
  name: ansible_playbook
  # name of the host
  hosts: test-kitchen
  # list of ansible galaxy requirements from the roles meta/main.yml
  requirements_path: dependencies.yml

platforms:
  - name: centos-7
    driver_config:
      image: geerlingguy/docker-centos7-ansible:latest
      run_command:
        - '/usr/sbin/sshd -D -o UseDNS=no -o UsePAM=no -o PasswordAuthentication=yes -o UsePrivilegeSeparation=no -o PidFile=/tmp/sshd.pid'
        - /usr/sbin/init
        - yum install -y git
        - yum install -y openssl
      privileged: true



suites:
  # suites found at /test/integration/$test-name
  - name: default
