---
driver:
  # using docker to test
  name: docker
  privileged: true
  run_command: /sbin/init

provisioner:
  # use an ansible playbook to provision our server
  name: ansible_playbook
  # name of the host
  hosts: test-kitchen
  # list of ansible galaxy requirements from the roles meta/main.yml
  requirements_path: dependencies.yml

platforms:
  - name: centos-7
    driver_config:
      image: guisea/centos7-ansible:latest
      platform: centos

suites:
  # suites found at /test/integration/$test-name
  - name: default
