---

language: python

services: mysql

python: "2.7"

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq aptitude python-apt python-pycurl

install:
  - pip install ansible ansible-lint

script:
  - echo localhost > inventory
  - ansible-lint *.yml
  - ansible-playbook --syntax-check -i inventory role.yml
  - ansible-playbook -i inventory role.yml --connection=local --sudo -vvvv
  - /usr/local/bin/automysqlbackup
