---
- name: apply host automysqlbackup configuration
  template:
    src: automysqlbackup.j2
    dest: /etc/automysqlbackup/automysqlbackup.conf
    group: root
    owner: root
    mode: "0600"
  tags:
    - automysqlbackup