---

- name: Ensure tmp dir exists
  file:
    path: /tmp/automysqlbackup
    state: directory
  tags:
    - automysqlbackup

- name: download automysqlbackup
  unarchive:
    src: "{{ automysqlbackup_download_url }}"
    dest: /tmp/automysqlbackup
    creates: /usr/local/bin/automysqlbackup
    remote_src: true
  tags:
    - automysqlbackup

- name: apply automysqlbackup configuration
  template:
    src: automysqlbackup.j2
    dest: /etc/default/automysqlbackup
    group: root
    owner: root
    mode: "0600"
  tags:
    - automysqlbackup

- name: remove the cron.daily file
  file:
    path: /etc/cron.daily/automysqlbackup
    state: absent
  tags:
    - automysqlbackup

- name: add automysqlbackup cron job
  cron:
    name: "automysqlbackup"
    minute: "{{ automysqlbackup_cron.minute }}"
    hour: "{{ automysqlbackup_cron.hour }}"
    day: "{{ automysqlbackup_cron.day }}"
    month: "{{ automysqlbackup_cron.month }}"
    weekday: "{{ automysqlbackup_cron.weekday }}"
    user: root
    job: "/usr/sbin/automysqlbackup"
  tags:
    - automysqlbackup
